### ISSUE TITLE
Out of Sync 

### ISSUE THREAD

**Issue by Terceirow** [aoenw/Hundred-Days#37]
I tried to present the game to five my friends. We tested one by one and all together. Always in six or seven seconds of the game, in Lan, by hamachi, this error appears. =(

**Comment by aoenw** [comment]
Hello @Terceirow, does anyone of you uses a steam version? I have similar reports but only concerning steam versions.

**Comment by Terceirow** [comment]
No steam versions! =(

**Comment by Terceirow** [comment]
Please help me !!! His version is so much more strategically !! Not anymore back to normal version without realistic tactic!

**Comment by aoenw** [comment]
1. I assume you all have identical versions of the game.
2. Do you have other mods installed?
3. Typically, an OOS appears likewise when using custom maps and putting them into the core game files.

**Comment by Yomguithereal** [comment]
Also: I assume you can play through hamachi with your friends usually without those OOS on the standard game?

**Comment by Terceirow** [comment]
Identical versions, installed together here in my house. Currently played the regular version without any problems!

**Comment by aoenw** [comment]
1. Can you try different maps, different settings etc.
2. Can you try with less players and tell me if this changes anything?
3. I'll try to regenerate the crc file ensuring the validity of the maps but I cannot do it right now.

**Comment by Terceirow** [comment]
We just test with two players, three players and four players. Tested in randons maps and four maps! Is there anything I can change?

**Comment by aoenw** [comment]
Ok, I checked the mod's crc file and it appears it is not correct. Here is what you are going to do:
- Copy the code below into a text file you will call `resources.xml`.

``` js
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rmfilecrc>
  <map name="NW Acropolis">3401448203</map>
  <map name="NW Alpine Pass">2815360874</map>
  <map name="NW Atlas Mountains">370875496</map>
  <map name="NW Black Forest">3857989053</map>
  <map name="NW Carpathian Mountains">934576771</map>
  <map name="NW Coast">327176286</map>
  <map name="NW Dark Forest">3233886886</map>
  <map name="NW Delta">4086016369</map>
  <map name="NW Finland">2299617096</map>
  <map name="NW Flood of the Nile">2464319387</map>
  <map name="NW Glacier">3218551805</map>
  <map name="NW Great Lakes">2492612543</map>
  <map name="NW Italian Peninsula">3364512425</map>
  <map name="NW Lake Baikal">2222695080</map>
  <map name="NW Litvonia">3716585179</map>
  <map name="NW Long River">790039234</map>
  <map name="NW Marshes">2559500649</map>
  <map name="NW Mountain Gap">1510165002</map>
  <map name="NW Northern Forests">3888872634</map>
  <map name="NW Northern Lakes">1537295697</map>
  <map name="NW Norway">615925380</map>
  <map name="NW Prussia Rivers">3092865175</map>
  <map name="NW Rhine">1303920790</map>
  <map name="NW Russian Lands">3841315556</map>
  <map name="NW Russian Winter">4245468094</map>
  <map name="NW Siberia">125870268</map>
  <map name="NW Spain">1904419540</map>
  <map name="NW Valley">349156284</map>
  <map name="NW Walachia">2530598557</map>
</rmfilecrc>
```
- Move the file under `AoEIII folder/data`.
- Then retry and tell me if this works. If it does, I'll release a hotfix of the mod.

**Comment by Terceirow** [comment]
Now is working perfectly! =D

**Comment by aoenw** [comment]
Well, that's a relief! I shall release a hotfix soon then.

**Comment by mikoo963** [comment]
Hi we have the same problem. We tried LAN but after few seconds it falls down. Tried adding resources file but still OOS. Please help
